# Hyprland configuration
# ~/.config/hypr/hyprland.conf
# exec-once = waybar & hyprpaper

# External monitor
monitor = eDP-1, disable
monitor = HDMI-A-1, 1440x900@74.98, 0x0, 1

# Keybindings
bind = SUPER, RETURN, exec, kitty
bind = SUPER, D, exec, rofi -show drun
# bind = SUPER, F, exec, nemo
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3

# Environment fixes
env = DISPLAY,1
env = QT_QPA_PLATFORM,wayland
env = GDK_BACKEND,wayland
env = CLUTTER_BACKEND,wayland
env = ELIBC_USE_WAYLAND,1
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1

# General
general {
    border_size = 2
    gaps_in = 3 # gaps between windows
    gaps_out = 6 # gaps between windows and monitor edges
    # gradient border
    col.active_border = rgba(e6e6faee) rgba(b57edccc) 45deg
    # classic lavender (light purple)
    # col.active_border = rgba(e6e6faee)  # Slightly transparent (0.9 alpha)
    # deeper lavender (more saturated)
    # col.active_border = rgba(b57edccc)  # Softer transparency
    # muted lavender (grayish-purple)
    # col.active_border = rgba(c3b1e1d9)  # Subtle and modern
}

# Aesthetics
decoration {
    rounding = 8
    active_opacity = 0.85
    inactive_opacity = 0.55
    fullscreen_opacity = 1.0

    blur {
        enabled = false
        size = 1
        passes = 1
        new_optimizations = on
        ignore_opacity = true
        xray = true
        # blurls = waybar
    }

    shadow {
        enabled = true
        range = 30
        render_power = 3
        color = 0x66000000
    }
}